#!/bin/bash 

echo "Running Vpl ++ Run Script - Vpl ++ Jlib runner V.1.0.0"
echo "Ingeniería de Sistemas - UFPS"

## Writte the vpl_execution program
echo "#!/bin/bash" >> $1/vpl_execution

## Compiling the classes
echo "javac -nowarn -encoding UTF-8  -cp "/usr/bin/VPLPlusPlus-jlib.jar" $1/*.java" >> $1/vpl_execution

## Remove the java files 
echo "rm -rf $1/*.java"  >> $1/vpl_execution

## Execute the just java
echo 'if test -f "main.class"; then' >> $1/vpl_execution
echo '    java main'>> $1/vpl_execution
echo 'else' >> $1/vpl_execution
echo '    echo "Main class not found (main.java)"' >> $1/vpl_execution
echo 'fi' >> $1/vpl_execution

## Make executable vpl_execution
chmod +x $1/vpl_execution